# Generated by Django 3.2.22 on 2024-03-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departements',
            old_name='DepartementId',
            new_name='DepartmentId',
        ),
    ]
